### ISSUE TITLE
Any way to increase the lock time?

### ISSUE THREAD

**Issue by soamaven** [CurrencyTycoon/eth-hodler#4]
Say one wants to lock for 6-12 months, anyway to have that be a parameter?

**Comment by CurrencyTycoon** [comment]
Thanks for asking.
If you know a little about smart contracts, you could take the contract source, modify the timeWait constant and then re-deploy the contract to your own address.
I was thinking about adding this feature where you could specify the time, however, decided not to because wanted to keep it simple,
